### 로그인
POST http://localhost:8080/api/auth/login
Content-Type: application/x-www-form-urlencoded

username=email0@example.com&password=Password1!

### 인증코드 발송
POST http://localhost:8080/api/auth/send-email-auth-code
Content-Type: application/json

{
  "email": "exampz@naver.com"
}

### 회원가입
POST http://localhost:8080/api/v0/auth/signup
Content-Type: application/json

{
  "name": "홍길동",
  "email": "example@naver.com",
  "password":"Password1!",
  "confirmPassword": "Password1!",
  "tellNumber": "010-7777-7777",
  "address": "서울시 용산구 351 오오오",
  "authCode": "131327"
}

### 테스트 get
GET http://localhost:8080/api/v0/auth/test


### 테스트 post
POST http://localhost:8080/api/v0/auth/test/post

### 게이트웨이
GET http://localhost:8080/actuator/gateway
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2Mm5mUW1ZSGgyZElsQjZLY3ZuWnlxaXYrdEMvOXVOR0FpR2pnOWNvTHFVPSIsIm1lbWJlcklkIjo1OCwicm9sZXMiOlt7ImF1dGhvcml0eSI6IlJPTEVfR0VORVJBTCJ9XSwiaWF0IjoxNzI1NTM3NDM1LCJleHAiOjE3MjU1NDEwMzV9.QVZi3Lb2GPi9mNVypIem9kRySWriRUY1XOWZnZ39wAg

